=== JULIELab/costosys/src/main/resources/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://julielab.de"
		   xmlns="http://julielab.de" elementFormDefault="qualified">

	<xs:element name="databaseConnectorConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DBSchemaInformation" minOccurs="0"
					maxOccurs="1"/>
				<xs:element ref="DBConnectionInformation" minOccurs="0"
					maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Schema -->
	<xs:element name="DBSchemaInformation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="activePostgresSchema" type="xs:string"
					minOccurs="0" maxOccurs="1"/>
				<xs:element name="activeTableSchema" type="xs:string"
					minOccurs="0" maxOccurs="1"/>
				<xs:element name="activeDataPostgresSchema" type="xs:string"
					minOccurs="0" maxOccurs="1"/>
				<xs:element name="dataTable" type="xs:string" minOccurs="0"
					maxOccurs="1"/>
				<xs:element ref="tableSchemas" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tableSchemas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tableSchema" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tableSchema">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="forEach" type="xs:string" use="optional"></xs:attribute>
			<xs:attribute name="binary" type="xs:boolean" use="optional"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="xpath" type="xs:string"></xs:attribute>
			<xs:attribute name="filename" type="xs:string"></xs:attribute>
			<xs:attribute name="regex" type="xs:string"></xs:attribute>
			<xs:attribute name="replaceWith" type="xs:string"></xs:attribute>
			<xs:attribute name="primaryKey" type="xs:boolean"></xs:attribute>
			<xs:attribute name="retrieve" type="xs:boolean"></xs:attribute>
			<xs:attribute name="timestamp" type="xs:boolean"></xs:attribute>
			<xs:attribute name="returnXMLFragment" type="xs:boolean"></xs:attribute>
			<xs:attribute name="returnValuesAsArray" type="xs:boolean"></xs:attribute>
			<xs:attribute name="concatString" type="xs:boolean"></xs:attribute>
			<xs:attribute name="extractFromFileName" type="xs:boolean"></xs:attribute>
			<xs:attribute name="mixedContent" type="xs:boolean"></xs:attribute>
			<xs:attribute name="resolveEntities" type="xs:boolean"></xs:attribute>
			<xs:attribute name="gzip" type="xs:boolean"></xs:attribute>
			<xs:attribute name="notNull" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>



	<!-- Connection -->
	<xs:element name="DBConnectionInformation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="activeDBConnection" type="xs:string"
					minOccurs="0" maxOccurs="1"/>
				<xs:element name="maxActiveDBConnections" type="xs:integer"
					minOccurs="0" maxOccurs="1"/>
				<xs:element ref="DBConnections" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="DBConnections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DBConnection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="DBConnection">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="url" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<!-- UIMA type system file locations for decoding of JeDIS binary XMI format -->

	<xs:element name="TypeSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== JULIELab/costosys/src/main/resources/defaultConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- no Doctype, XML Schema used instead -->
<databaseConnectorConfiguration
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://julielab.de"
		xsi:schemaLocation="http://julielab.de https://github.com/JULIELab/costosys/blob/v1.0.1/src/main/resources/configuration.xsd">
	<DBSchemaInformation>
		<activePostgresSchema>test</activePostgresSchema>
		<activeTableSchema/>
		<activeDataPostgresSchema>_data</activeDataPostgresSchema>
		<dataTable>_data</dataTable>
		<tableSchemas>
			<tableSchema name="medline_2017"
				forEach="/PubmedArticleSet/PubmedArticle/MedlineCitation">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xml" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
			</tableSchema>
			<tableSchema name="medline_2016" forEach="/MedlineCitationSet/MedlineCitation">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xml" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
			</tableSchema>
			<tableSchema name="pubmed_gzip"
				forEach="/PubmedArticleSet/PubmedArticle/MedlineCitation">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xml" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
			</tableSchema>
			<tableSchema name="xmi_text" forEach=".">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xmi" type="text" xpath="." returnXMLFragment="true"
					retrieve="true"/>
				<field name="max_xmi_id" type="integer" xpath="." retrieve="true"/>
				<field name="sofa_mapping" type="text" xpath="." retrieve="true"/>
			</tableSchema>
			<tableSchema name="xmi_annotation" forEach=".">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="false"/>
				<field name="xmi" type="text" xpath="." returnXMLFragment="true"
					retrieve="true"/>
			</tableSchema>
			<tableSchema name="xmi_text_gzip" forEach=".">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xmi" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
				<field name="max_xmi_id" type="integer" xpath="." retrieve="true"/>
				<field name="sofa_mapping" type="text" xpath="." retrieve="true"/>
			</tableSchema>
			<!-- This schema is supposed to only get the max_xmi_id field value of
				the xmi_text_gzip schema. -->
			<tableSchema name="max_id_addition" forEach=".">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="false"/>
				<field name="xmi" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="false" gzip="true"/>
				<field name="max_xmi_id" type="integer" xpath="." retrieve="true"/>
			</tableSchema>
			<tableSchema name="xmi_annotation_gzip" forEach=".">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="false"/>
				<field name="xmi" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
			</tableSchema>
			<tableSchema name="dbc_junit_gzip" forEach="/MedlineCitationSet/MedlineCitation">
				<field name="pmid" type="text" xpath="PMID" primaryKey="true"
					retrieve="true"/>
				<field name="xml" type="bytea" xpath="." returnXMLFragment="true"
					retrieve="true" gzip="true"/>
			</tableSchema>
		</tableSchemas>
	</DBSchemaInformation>
	<DBConnectionInformation>
		<activeDBConnection></activeDBConnection>
		<maxActiveDBConnections>1</maxActiveDBConnections>
		<DBConnections>
			<DBConnection url="" name="" />
		</DBConnections>
	</DBConnectionInformation>
</databaseConnectorConfiguration>
